import { useEffect, useState } from 'react'
import { api } from '../lib/api'
import type { LibraryBook, LibraryLoan, Student } from '../types'

export function LibraryPage() {
  const [books, setBooks] = useState<LibraryBook[]>([])
  const [loans, setLoans] = useState<LibraryLoan[]>([])
  const [students, setStudents] = useState<Student[]>([])
  const [title, setTitle] = useState('')
  const [author, setAuthor] = useState('')
  const [copies, setCopies] = useState(1)
  const [bookId, setBookId] = useState('')
  const [studentId, setStudentId] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [message, setMessage] = useState<string | null>(null)
  async function refresh() { const [b, l, s] = await Promise.all([api.libraryBooks(), api.libraryLoans(), api.students()]); setBooks(b); setLoans(l); setStudents(s); if (!bookId && b[0]) setBookId(b[0].id); if (!studentId && s[0]) setStudentId(s[0].id) }
  useEffect(() => { refresh().catch(e => setError(e.message)) }, [])
  async function addBook() { setError(null); setMessage(null); try { const b = await api.createLibraryBook({ title, author, total_copies: copies }); setMessage(`Livre ajouté : ${b.title}`); setTitle(''); setAuthor(''); await refresh() } catch(e) { setError(e instanceof Error ? e.message : 'Erreur livre') } }
  async function loan() { setError(null); setMessage(null); try { const l = await api.createLibraryLoan({ book_id: bookId, student_id: studentId }); setMessage(`Prêt créé : ${l.book_title} à ${l.student_name}`); await refresh() } catch(e) { setError(e instanceof Error ? e.message : 'Erreur prêt') } }
  async function ret(id: string) { setError(null); setMessage(null); try { await api.returnLibraryLoan(id); setMessage('Livre retourné.'); await refresh() } catch(e) { setError(e instanceof Error ? e.message : 'Erreur retour') } }
  return <div className="space-y-6"><div><p className="app-kicker">Bibliothèque</p><h1 className="mobile-page-title mt-2 text-4xl font-black text-slate-950">Livres et prêts</h1><p className="mt-2 text-sm text-slate-500">Gestion des ouvrages, exemplaires disponibles, prêts et retours.</p></div>{error && <div className="rounded-2xl bg-red-50 p-4 text-red-700">{error}</div>}{message && <div className="rounded-2xl bg-emerald-50 p-4 text-emerald-700">{message}</div>}<section className="grid gap-4 lg:grid-cols-2"><div className="app-card rounded-[2rem] p-5"><h2 className="text-xl font-black">Ajouter un livre</h2><div className="mt-4 grid gap-3"><input value={title} onChange={e => setTitle(e.target.value)} placeholder="Titre" className="rounded-2xl border border-slate-200 px-4 py-3"/><input value={author} onChange={e => setAuthor(e.target.value)} placeholder="Auteur" className="rounded-2xl border border-slate-200 px-4 py-3"/><input type="number" value={copies} onChange={e => setCopies(Number(e.target.value))} min={1} className="rounded-2xl border border-slate-200 px-4 py-3"/><button onClick={addBook} className="rounded-2xl bg-blue-700 px-5 py-3 font-black text-white">Ajouter</button></div></div><div className="app-card rounded-[2rem] p-5"><h2 className="text-xl font-black">Créer un prêt</h2><div className="mt-4 grid gap-3"><select value={bookId} onChange={e => setBookId(e.target.value)} className="rounded-2xl border border-slate-200 px-4 py-3">{books.map(b => <option key={b.id} value={b.id}>{b.title} ({b.available_copies} dispo.)</option>)}</select><select value={studentId} onChange={e => setStudentId(e.target.value)} className="rounded-2xl border border-slate-200 px-4 py-3">{students.map(s => <option key={s.id} value={s.id}>{s.matricule} — {s.full_name}</option>)}</select><button onClick={loan} className="rounded-2xl bg-slate-950 px-5 py-3 font-black text-white">Prêter</button></div></div></section><section className="grid gap-3 md:grid-cols-2">{books.map(b => <article key={b.id} className="rounded-2xl border border-slate-200 bg-white p-4"><h3 className="font-black">{b.title}</h3><p className="text-sm text-slate-500">{b.author || 'Auteur non renseigné'} · {b.available_copies}/{b.total_copies} disponible(s)</p></article>)}</section><section className="app-card rounded-[2rem] p-5"><h2 className="text-xl font-black">Prêts récents</h2>{loans.map(l => <div key={l.id} className="mt-3 flex flex-col gap-2 rounded-2xl bg-slate-50 p-3 sm:flex-row sm:items-center sm:justify-between"><p><b>{l.book_title}</b> — {l.matricule} {l.student_name} · {l.status}</p>{l.status !== 'returned' && <button onClick={() => ret(l.id)} className="rounded-xl bg-emerald-600 px-3 py-2 text-sm font-black text-white">Retour</button>}</div>)}</section></div>
}
